const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const source = fs.readFileSync("web/app.js", "utf8");
const start = source.indexOf("function releaseAvailability(");
assert.ok(start >= 0, "release controls need state-aware availability");
const context = {};
vm.createContext(context);
vm.runInContext(source.slice(start, source.indexOf("\nfunction applyReleaseControls", start)), context);
const policy = {error_threshold:0.05, max_sample_age_seconds:30};
const state = {status:"canary", last_decision:{state:"observe", error_ratio:0, sample_time:1000}};
const check = (release, authed=true, busy=false, now=1000) => context.releaseAvailability(release, policy, authed, busy, now);
assert.equal(check(state).start, false);
assert.equal(check(state).advance, true);
assert.equal(check(state, true, false, 1031).advance, false);
assert.equal(check({...state, last_decision:{state:"unknown"}}).advance, false);
assert.equal(check({...state, last_decision:{...state.last_decision, error_ratio:0.06}}).advance, false);
assert.equal(check({...state, reconcile_required:true}).advance, false);
assert.equal(check(state, false).rollback, false);
assert.equal(check(state, true, true).rollback, false);
assert.equal(check({...state, last_decision:{state:"unknown"}}).rollback, true);
assert.equal(check({status:"stable"}).start, true);
assert.equal(check({status:"completed"}).start, false);
console.log("Release UI availability checks passed");
